name: Continuous Delivery

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/continuous-delivery.yml'
      - 'scripts/sitemapGenerator.mjs'
      - 'package.json'
      - 'yarn.lock'
      - 'Dockerfile'

jobs:
  PublishSkyraPw:
    name: Publish Birthdayy.xyz image to container registries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Birthdayy.xyz  Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: ghcr.io/birthdayybot/birthdayy.xyz:latest